# Generated by Django 4.1.3 on 2022-11-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=55)),
                ('text', models.TextField()),
                ('languages', models.CharField(max_length=55)),
                ('items', models.CharField(max_length=55)),
                ('it_texnolog', models.CharField(max_length=55)),
            ],
        ),
    ]
